#!/bin/sh

patterns=( '?' 'Locally Added' 'Locally Modified' )
(cvs -Q status -R . > /tmp/.cvs_status) 2> /dev/null
for i in "${patterns[@]}"; do
  cat /tmp/.cvs_status | grep -i "$i"
done
rm /tmp/.cvs_status
