#!/bin/tcsh

setenv LD_LIBRARY_PATH $BINDIR/../lib
if($1 == cmake) then
  echo set up for cmake build...
  setenv BUILD_DIR ${TEMP}/builds/$ASE_VERSION
  setenv ASE_HOME ${BUILD_DIR}/ship/rhel-x86_64-5.2/ase-v$ASE_VERSION
  setenv SERVER_EXEC ${ASE_HOME}/bin/exec/aseserver
  setenv UTIL_EXEC ${ASE_HOME}/bin/exec/aseutility
else
  echo set up for algomake build...
  setenv ASE_HOME $SOURCE/ASE-${ASE_VERSION}/ship/${PLATFORM_WIDE}/ase-v
  setenv SERVER_EXEC $SOURCE/ASE-${ASE_VERSION}/obj/${PLATFORM_WIDE}/ScenarioEngine/aseserver
endif
