#!/bin/sh

BUCKET_NAME=$1
TEST_NAME=$2
TEST_BASELINE_DIR=$BUILD_AREA/Harness/ASEServer/Baselines/$BUCKET_NAME/$TEST_NAME

ListAllXLSFilesInBaselineDir() {
    V=$1
    X=`ls $TEST_BASELINE_DIR/*xls | xargs -i basename {} | sed "s/.xls$//" | xargs echo`

    if [ ! -n "$X" ]; then
	X="no_XLS_files_found_in_baseline_directory"
    fi

    eval $V=\"$X\"
}

ListAllXLSFilesInBaselineDir "RESULT_FILES";

for AFILE in $RESULT_FILES
do
    RSLT=TEMP/output/$BUCKET_NAME/$TEST_NAME/$PLATFORM/$AFILE.xls
    BSLN=$TEST_BASELINE_DIR/$AFILE.xls

    if [ ! -f "$BSLN" ]; then
		echo test error:  baseline file $BSLN not found
		exit 1
    fi

    if [ ! -f "$RSLT" ]; then
		echo test failed: result file $RSLT not found
		exit 1
    fi

    head -n 18 $RSLT > $BSLN
done

